# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ObserveAgent < Formula
    desc "Observe-Agent is a tool for collecting and exporting metrics from your infrastructure."
    homepage "https://observeinc.com/"
    version "0.1.10-SNAPSHOT-78d323f"
    license "Apache-2.0"

    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/observeinc/observe-agent/releases/download/v0.1.10/observe-agent_Darwin_arm64.tar.gz"
        sha256 "65241c0e3b08d92781d89b6243c1f481ffde7489a64955043776086289924ab7"

        def install
          bin.install "observe-agent"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/observeinc/observe-agent/releases/download/v0.1.10/observe-agent_Darwin_x86_64.tar.gz"
        sha256 "df43cd340d8e90d3dc314e2e5d297558637ead1baf48d05d796d3fcfb6389b20"

        def install
          bin.install "observe-agent"
        end
      end
    end

    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/observeinc/observe-agent/releases/download/v0.1.10/observe-agent_Linux_arm64.tar.gz"
        sha256 "b7338980d5abd4f21aff21d3336d16f822edb510ac47fda0ef1372f86896d0d3"

        def install
          bin.install "observe-agent"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/observeinc/observe-agent/releases/download/v0.1.10/observe-agent_Linux_x86_64.tar.gz"
        sha256 "5b9df37e7f84c05d8538568a8b18a71042b5fbb71c4c037825613dcf6e805e27"

        def install
          bin.install "observe-agent"
        end
      end
    end
  end